# -*- coding: utf-8 -*-
"""ConvertRDDtoDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgBqMrIJZOe67UJStUTcZ96Cg7eme4Kb
"""

#ways to convert rdd to df
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("RDDtoDF").getOrCreate()
sc = spark.sparkContext
rdd = sc.parallelize([
    (101, "John", 50000),
    (102, "Alice", 60000),
    (103, "Bob", 55000)
])

#using toDF()
df=rdd.toDF(['id','name','salary'])
df.show()

#spark.createDataFrame()
df=spark.createDataFrame(rdd,['id','name','salary'])
df.show()

#using createDataFrame() with row
from pyspark.sql import Row
rdd=sc.parallelize([
    Row(id=101,name="John",salary=50000),
    Row(id=102,name="Alice",salary=60000),
    Row(id=103,name="Bob",salary=55000)
])
df=rdd.toDF()
df.show()

#using structField
from pyspark.sql.types import *
schema=StructType([StructField('id',IntegerType(),True),
                   StructField('name',StringType(),True),
                   StructField('salary',IntegerType(),True)])
df=spark.createDataFrame(rdd,schema)
df.show()

#using structfield()
schema=StructType([StructField('id',IntegerType(),False),
                   StructField('name',StringType(),False),
                   (StructField('Salary',IntegerType(),True)
                   )])
df=spark.createDataFrame(rdd,schema)
df.show()

#convert key-value RDD
pairrdd=sc.parallelize([('HR',10),('IT',20),('sales',30)])
df=pairrdd.toDF(['DEpt','employees'])
df.show()

#RDD of dictionaries
rdd=sc.parallelize([{'name':'John','age':30},{'name':'Alice','age':25},{'name':'Bob','age':35}])
df=rdd.toDF()
df.show()

#rdd of lists
rdd=sc.parallelize([[101,'A',50000],[102,'B',60000]])
df=spark.createDataFrame(rdd,['id','name','salary'])
df.show()

#rdd of single values
rdd=sc.parallelize(['Spark','Python','SQL'])
df=rdd.map(lambda x:(x,)).toDF(['Technology'])
df.show()

#ways to convert array (list) to dataframe
#array/list
#createDataFrame from list of tuples
data=[(101,'a',50000),(102,'b',60000),(103,'c',70000)]
df=spark.createDataFrame(data,['id','name','salary'])
df.show()

#create DataFRame from lists of lists:
data=[[101,'d',50000],[102,'e',60000],[103,'f',70000]]
df=spark.createDataFrame(data,['id','name','salary'])
df.show()

#List → RDD → DataFrame
data = [
    (101, "John", 50000),
    (102, "Alice", 60000)
]

rdd = sc.parallelize(data)

df = rdd.toDF(["id", "name", "salary"])

df.show()

# # Module 2: RDD to DataFrame
# # • Task 4: Create an RDD and convert it to a DataFrame.
# from pyspark.sql import SparkSession
# from pyspark.sql import Row
# spark=SparkSession.builder.appName("RDDtoDF").getOrCreate()
# sc=spark.sparkContext
# # rdd=sc.parallelize([
# #     (101,'John',50000),
# #     (102,'Alice',60000),
# #     (103,'Bob',55000)
# # ])
# # df=rdd.toDF(['id','name','salary'])
# # df.show()
# # • Task 5: Read a text file into an RDD and convert it to a DataFrame.

# rdd=sc.textFile('input.txt')
# for row in rdd.collect():
#   print(row)
# rdd1=rdd.map(lambda x:Row(value=x))
# df=spark.createDataFrame(rdd1)
# df.show()
# # • Task 6: Convert a DataFrame back to an RDD and print rows using foreach
# rdd2=df.rdd.map(lambda x:x.value)
# rdd2.foreach(print)

# Create a dummy input.txt file in Google Colab
with open("input.txt", "w") as f:
    f.write("Hello World\n")
    f.write("Welcome to PySpark\n")
    f.write("RDD to DataFrame tutorial\n")

print("File 'input.txt' created successfully!")

