# -*- coding: utf-8 -*-
"""RDDTransformations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bsH9GCLee3rWlQPXf67nFYTAGxrxnFU
"""

from  pyspark.sql import SparkSession
spark=SparkSession.builder.appName("Narrow Transformations").getOrCreate()
l=[1,2,3,4]
rdd=spark.sparkContext.parallelize(l)
res=rdd.map(lambda x:x*2)
print(res.collect())

#flatmap()
l=["Hello world"]
rdd=spark.sparkContext.parallelize(l)
res=rdd.flatMap(lambda x:x.split(" "))
print(res.collect())
#

#filter
l=[1,2,3,4,5,6,7,8,9,10]
rdd=spark.sparkContext.parallelize(l)
res=rdd.filter(lambda x:x%2==0)
print(res.collect())

#mapPartitions
# l=[1,2,3,4,5]
# rdd=spark.sparkContext.parallelize(l)
# res=rdd.mapPartitions(lambda x:iter([sum(x)]))
# print(res.collect())
def fun(it):
  yield sum(it)
rdd.mapPartitions(fun).collect()

#mapPartitionsWithIndex()
def fun(index,iter):
  return [(index,list(iter))]
rdd.mapPartitionsWithIndex(fun).collect()

print(rdd.glom().collect())

#sample()
print(rdd.sample(True,0.1,4))
print(rdd.collect())

#union
rdd=spark.sparkContext.parallelize([1,3,4])
rdd2=spark.sparkContext.parallelize([2,3,4])
print(rdd.union(rdd2).collect())

#coalesec:
rdd = spark.sparkContext.parallelize([10, 20, 30, 40], 4)
print("before:", rdd.getNumPartitions())
print(rdd.glom().collect())
coalesced_rdd = rdd.coalesce(2)
print("New partitions:", coalesced_rdd.getNumPartitions())
print(coalesced_rdd.glom().collect())

#keys()
rdd=spark.sparkContext.parallelize([(1,100),(2,200),(1,200)])
print(rdd.keys().collect())

#values()
rdd=spark.sparkContext.parallelize([(1,100),(2,200),(1,200)])
print(rdd.values().collect())

#zip()
rdd1=spark.sparkContext.parallelize([('A',1),('B',2),('A',2)])
rdd2=spark.sparkContext.parallelize([('C',3),('B',1),('D',4)]) # Modified to have the same number of elements as rdd1
print(rdd1.zip(rdd2).collect())

#zipWithIndex()
rdd1=spark.sparkContext.parallelize([('A',1),('B',2),('A',2)])
rdd2=spark.sparkContext.parallelize([('C',3),('B',1),('D',4)])
print(rdd1.zipWithIndex().collect())
print(rdd2.zipWithIndex().collect())

#zipWithUniqueId()
rdd1=spark.sparkContext.parallelize([('A',1),('B',2),('A',2)])
rdd2=spark.sparkContext.parallelize([('C',3),('B',1),('D',4)])
print(rdd1.zipWithUniqueId().collect())
print(rdd2.zipWithUniqueId().collect())

print(rdd.pipe('cat').collect())

#wide transformations
#groupByKey()
rdd=spark.sparkContext.parallelize([('A',2),('B',2),('A',1)])
rdd1=rdd.groupByKey()
rdd_final=rdd1.mapValues(list)
print(rdd_final.collect())

#reduceByKey()
rdd=spark.sparkContext.parallelize([('A',2),('B',2),('A',1)])
rdd1=rdd.reduceByKey(lambda x,y:x+y)
print(rdd1.collect())

#AggregateByKey()
rdd=spark.sparkContext.parallelize([('A',10),('A',30),('B',20),('B',20)])
z=(0,0)
rdd1=lambda x,y:(x[0]+y,x[1]+1)
com=lambda s,c:(s[0]+c[0],s[0]+c[1])
sum=rdd.aggregateByKey(z,rdd1,com)
avg=sum.mapValues(lambda total:total[0]/total[1])
print(avg.collect())

#combinebykey()
rdd=spark.sparkContext.parallelize([('A',10),('A',30),('B',20),('B',20)])
create_comb=lambda x:(x,1)
merge=lambda x,y:(x[0]+y,x[1]+1)
meg=lambda x,y:(x[0]+y[0],x[1]+y[1])
rdd1=rdd.combineByKey(create_comb,merge,meg)
print(rdd1.collect())

#foldbykey()
rdd=spark.sparkContext.parallelize([('A',10),('A',30),('B',20),('B',20)])
rdd1=rdd.foldByKey(1,lambda x,y:x*y)
print(rdd1.collect())

#sortbykey()
rdd=spark.sparkContext.parallelize([('A',10),('B',30),('D',20),('C',20)])
rdd1=rdd.sortByKey()
print(rdd1.collect())

#sortBy()
rdd=spark.sparkContext.parallelize([('A',10),('B',30),('D',20),('C',20)])
rdd1=rdd.sortBy(lambda x:x[1])
print(rdd1.collect())

#join
employees_rdd = spark.sparkContext.parallelize([
    (101, "Alice"),
    (102, "Bob"),
    (103, "Charlie"),
    (104, "David")
])
departments_rdd = spark.sparkContext.parallelize([
    (101, "HR"),
    (102, "Engineering"),
    (103, "Finance"),
    (105, "Marketing")  # Notice 105 does not exist in the employee RDD
])
joined=employees_rdd.join(departments_rdd)
print(joined.collect())

#leftOuterjoin()
employees_rdd = spark.sparkContext.parallelize([
    (101, "Alice"),
    (102, "Bob"),
    (103, "Charlie"),
    (104, "David")
])
departments_rdd=spark.sparkContext.parallelize([
    (101, "HR"),
    (102, "Engineering"),
    (103, "Finance"),
    (105, "Marketing")
lt=employees_rdd.leftOuterJoin(departments_rdd)
print(lt.collect())

#rightOuterJoin()
employees_rdd = spark.sparkContext.parallelize([
    (101, "Alice"),
    (102, "Bob"),
    (103, "Charlie"),
    (104, "David")])
departments_rdd=spark.sparkContext.parallelize([
    (101, "HR"),
    (102, "Engineering"),
    (103, "Finance"),
    (105, "Marketing")
])
rt=employees_rdd.rightOuterJoin(departments_rdd)
print(rt.collect())

#fullOuterJoin()
employees_rdd = spark.sparkContext.parallelize([
    (101, "Alice"),
    (102, "Bob"),
    (103, "Charlie"),
    (104, "David")
])
departments_rdd=spark.sparkContext.parallelize([
    (101, "HR"),
    (102, "Engineering"),
    (103, "Finance"),
    (105, "Marketing")])
fj=employees_rdd.fullOuterJoin(departments_rdd)
print(fj.collect())

#cogroup()
rdd1=spark.sparkContext.parallelize([('A',1),('B',3)])
rdd2=spark.sparkContext.parallelize([('A',2)])
cg=rdd1.cogroup(rdd2)
rd_cg=cg.mapValues(lambda x:[list(i) for i in x])
print(rd_cg.collect())

#intersection()
rdd1=spark.sparkContext.parallelize([1,2,3,4,5,5])
rdd2=spark.sparkContext.parallelize([1,4,2,7])
inter=rdd1.intersection(rdd2)
print(inter.collect())

#distinct()
rdd1=spark.sparkContext.parallelize([1,2,3,4,5,5])
rdd2=spark.sparkContext.parallelize([1,4,2,7])
rdd3=rdd1.distinct()
print(rdd3.collect())

