# -*- coding: utf-8 -*-
"""RDDTask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FeTKN0BODxMifOxS-_-U-4-yuz04iR3j
"""

# # Creating RDDs (15 Questions)

# # 1. Create an RDD from a Python list.
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName("Task").getOrCreate()
rdd=spark.sparkContext.parallelize([1,2,3,4,5])
# rdd.collect()
# # 2. Create an RDD from a tuple.
# t=('sunitha','angel','grace')
# rdd1=spark.sparkContext.parallelize(t)
# rdd1.collect()
# # 3. Create an RDD using range().
# rdd3=spark.sparkContext.parallelize(range(1,10))
# rdd3.collect()
# # 4. Create an RDD from a text file.
# rdd4=spark.sparkContext.textFile('sample.txt')
# print(rdd4.collect())
# # 5. Create an RDD using wholeTextFiles().
# rdd5=spark.sparkContext.wholeTextFiles('sample_data,sample1.txt')
# print(rdd5.collect())
# # 6. Difference between parallelize() and textFile().
# # 7. Create an empty RDD.
# rdd6=spark.emptyRDD
# print(rdd6)
# 8. Create Pair RDD.
# s=[('A',70),('B',80)]
# rdd7=spark.sparkContext.parallelize(s)
# print(rdd7.collect())
# # 9. Create an RDD with 10 partitions.
# l=[1,2,3,4,5,6,7,8,9,10]
# rdd8=spark.sparkContext.parallelize(l,10)
# print(rdd8.collect())
# print(rdd8.getNumPartitions())
# print(rdd8.glom())
# # 10. Read multiple files into one RDD.
# rdd9= spark.sparkContext.textFile("*.txt")
# print(rdd9.collect())
# 11. Create an RDD from CSV.
# rdd10=spark.sparkContext.textFile('emp.csv')
# print(rdd10.collect())
# 12. Read JSON into RDD.
# rdd11=spark.sparkContext.textFile('emp.json')
# print(rdd11.collect())
# 13. Create RDD using Hadoop input.
# rdd = sc.textFile("hdfs://localhost:9000/data/employees.txt")
# print(rdd.collect())  or
# rdd = sc.hadoopFile(
#     "hdfs://localhost:9000/data",
#     "org.apache.hadoop.mapred.TextInputFormat",
#     "org.apache.hadoop.io.LongWritable",
#     "org.apache.hadoop.io.Text"
# )
# 14. Explain SparkContext.parallelize().
# parallelize() distributes a local collection across the Spark cluster and creates an RDD.

# Syntax:sc.parallelize(collection, numPartitions)
# collection → Local iterable (list, tuple, range, etc.)
# numPartitions → Optional number of partitions
# Example
# rdd = sc.parallelize([10,20,30], 3)
# 15. Explain minPartitions parameter.
# minPartitions specifies the minimum number of partitions Spark should create
#  when reading data from external storage (such as with textFile()).

# Examplerdd = sc.textFile("employees.txt", minPartitions=5)

# print(rdd.getNumPartitions())
# Why use it?
# Increases parallelism for large files.
# Helps distribute work more evenly across executors.
# Spark may create more than the requested number
# if required by the input format, but not fewer.

# 6. Difference between parallelize() and textFile().

# parallelize()                                                      	textFile()
# Creates an RDD from local Python collections	                  Reads data from files
# Used for testing or small data	                                Used in production
# Data already exists in memory	                                  Data comes from storage
# Accepts lists, tuples, sets, etc.                               Accepts file paths (local or distributed)

