# -*- coding: utf-8 -*-
"""readwriteDFFiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BgRhorXK9ljncnIeF9uzuypAO0VRzso
"""

from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('DF Files').getOrCreate()
df=spark.read.csv('sample_data/emp.csv')
df

df=spark.read.option('header','true').csv('sample_data/emp.csv')
df.show()

df=spark.read.option('header','true').option('inferSchema','true').csv('sample_data/emp.csv')
df
df.show()

df = spark.read \
    .option("header", "true") \
    .option("delimiter", ",") \
    .option("inferSchema", "true") \
    .csv("sample_data/emp.csv")
df.show()

#using format()
df=spark.read.format('csv').option('header','true').load('sample_data/emp.csv')
df.show()

#reading json
df=spark.read.json('sample_data/emp.json')
df

#using fomart()
df=spark.read.format('json').load('sample_data/emp.json')
df.show()

#multiline json
df=spark.read.option('multiline','true').json('sample_data/emp.json')
df.show()

#read parquet
df=spark.read.parquet('sample_data/flight_data.parquet')
df.show()

#using format()
df=spark.read.format('parquet').load('sample_data/flight_data.parquet')
df.show()

#read ORC
!pip install pandas pyarrow

import pandas as pd

import pyarrow
import pyarrow.orc as orc
data={
    'User_ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [95.5, 88.0, 92.3]
}
df=pd.DataFrame(data)
table=pyarrow.Table.from_pandas(df)
orc.write_table(table,'sample_data/emp.orc')

df=spark.read.orc('sample_data/emp.orc')
df.show()



#using format
df=spark.read.format('orc').load('sample_data/emp.orc')
df.show()

#read text file
df=spark.read.text('input.txt')
df.show()
#using format
# df=spark.read.format('text').load('input.txt')

# #read avro
# df=spark.read.format('avro').load('emp.avro')
# #read xml
# df=spark.read.format('xml').option('rowing','employee').load('emp.xml')
# #read delta
# df=spark.read.format('delta').load('emp_delta')
# #read binary files
# df=spark.read.format('binaryFile').load('images/')
# #read database(JDBC)
# df=spark.read.format('jdbc').option("url", "jdbc:mysql://localhost:3306/company")
#     .option("dbtable", "employee")
#     .option("user", "root")
#     .option("password", "root")
#     .load()
# #read hive table
# df = spark.read \
#     .format("jdbc") \
#     .option("url", "jdbc:mysql://localhost:3306/company") \
#     .option("query", "SELECT * FROM employee WHERE salary > 50000") \
#     .option("user", "root") \
#     .option("password", "root") \
#     .load()

# #reading multiple files
# df=spark.read.csv(['sample_data/emp.csv','sample_data/emp2.csv'])
# df.show().


# #using wildcard operator
# df=spark.read.csv('sample_data/*.csv')
# df.show()

#read entire file
# df=spark.read.csv('sample_data/')

